<?php
/*
 *  Made by The_stas (stashenko)
 *  https://github.com/stashenko/NamelessMC-v2.0.0-pr5
 *  NamelessMC version 2.0.0-pr5
 *
 *  License: MIT
 *
 *  Russian Language - Admin
 */

$language = array(
	/*
	 *  Admin Control Panel
	 */
	// Login
	're-authenticate' => 'Пожалуйста, повторите аутентификацию',

	// Sidebar
	'dashboard' => 'Приборная доска',
	'configuration' => 'Конфигурация',
	'layout' => 'Раскладка',
	'user_management' => 'Пользователи',
	'admin_cp' => 'Админ панель',
	'administration' => 'Администрация',
	'overview' => 'Обзор',
	'core' => 'Ядро',
	'integrations' => 'Интеграции',
	'minecraft' => 'Minecraft',
	'modules' => 'Модули',
	'security' => 'Безопасность',
	'sitemap' => 'Карта сайта',
	'styles' => 'Стили',
	'users_and_groups' => 'Пользователи и группы',

	// Overview
	'running_nameless_version' => 'NamelessMC версии <strong>{x}</strong>', // Don't replace "{x}"
	'running_php_version' => 'PHP версии <strong>{x}</strong>', // Don't replace "{x}"
	'statistics' => 'Статистика',
	'registrations' => 'Регистрация',
	'topics' => 'Темы',
	'posts' => 'Сообщений',
	'notices' => 'Уведомления',
	'no_notices' => 'Нет уведомлений',
	'email_errors_logged' => 'Ошибки электронной почты были зарегистрированы',

	// Core
	'settings' => 'Настройки',
	'general_settings' => 'Общие настройки',
	'sitename' => 'Название сайта',
	'default_language' => 'Язык по умолчанию',
	'default_language_help' => 'Пользователи смогут выбирать из любых установленных языков.',
	'install_language' => 'Установить язык',
	'update_user_languages' => 'Обновить языки пользователя',
	'update_user_languages_warning' => 'Это обновит язык для всех пользователей на вашем сайте, даже если они уже выбрали другой!',
	'updated_user_languages' => 'Языки пользователей были обновлены.',
	'installed_languages' => 'Все новые языки успешно установлены.',
	'default_timezone' => 'Часовой пояс по умолчанию',
	'registration' => 'Регистрация',
	'enable_registration' => 'Включить регистрацию?',
	'verify_with_mcassoc' => 'Проверить учетные записи пользователей с MCAssoc?',
	'email_verification' => 'Включить подтверждение по электронной почте?',
	'registration_settings_updated' => 'Настройки регистрации успешно обновлены.',
	'homepage_type' => 'Тип домашней страницы',
	'post_formatting_type' => 'Тип формата сообщения',
	'portal' => 'Портал',
	'private_profiles' => 'Частные профили',
	'missing_sitename' => 'Пожалуйста, введите название сайта длиной от 2 до 64 символов.',
	'missing_contact_address' => 'Пожалуйста, введите контактный адрес электронной почты длиной от 3 до 255 символов.',
	'use_friendly_urls' => 'Дружественные URL',
	'use_friendly_urls_help' => 'ВАЖНО: Ваш сервер должен быть настроен на использование файлов mod_rewrite и .htaccess, чтобы это работало.',
	'config_not_writable' => 'Ваш файл <strong>core/config.php</strong> недоступен для записи. Пожалуйста, проверьте права доступа к файлам.',
	'settings_updated_successfully' => 'Общие настройки успешно обновлены.',
	'social_media' => 'Социальные сети',
	'youtube_url' => 'Youtube URL',
	'twitter_url' => 'Twitter URL',
	'twitter_dark_theme' => 'Использовать темную тему Twitter?',
	'discord_id' => 'Discord Server ID',
	'discord_widget_theme' => 'Тема Discord Widget',
	'dark' => 'Темная',
	'light' => 'Светлая',
	'google_plus_url' => 'Google Plus URL',
	'facebook_url' => 'Facebook URL',
	'social_media_settings_updated' => 'Настройки социальных сетей успешно обновлены.',
	'successfully_updated' => 'Успешно обновлено',
    'debugging_and_maintenance' => 'Отладка и обслуживание',
    'debugging_settings_updated_successfully' => 'Настройки отладки успешно обновлены.',
    'enable_debug_mode' => 'Включить режим отладки?',
	'force_https' => 'Принудительно https?',
	'force_https_help' => 'Если включено, все запросы на ваш сайт будут перенаправлены на https. Для корректной работы у вас должен быть действующий SSL-сертификат.',
	'force_www' => 'Принудительно www?',
	'contact_email_address' => 'Контактный адрес электронной почты',
	'emails' => 'Emails',
	'email_errors' => 'Ошибки электронной почты',
	'registration_email' => 'Электронный адрес регистрации',
	'contact_email' => 'Почта для связи',
	'forgot_password_email' => 'Забыли пароль Email',
	'unknown' => 'Неизвестный',
	'delete_email_error' => 'Удалить ошибку',
	'confirm_email_error_deletion' => 'Вы уверены, что хотите удалить эту ошибку?',
	'viewing_email_error' => 'Просмотр ошибок',
	'unable_to_write_email_config' => 'Невозможно записать в файл <strong>core/email.php</core>. Пожалуйста, проверьте права доступа к файлам.',
	'enable_mailer' => 'Включить PHPMailer?',
	'enable_mailer_help' => 'Включите, если электронные письма не отправляются по умолчанию. Использование PHPMailer требует, чтобы у вас была служба, способная отправлять электронные письма, например, Gmail или SMTP-провайдер.',
	'outgoing_email' => 'Исходящий адрес электронной почты',
	'outgoing_email_info' => 'Это адрес электронной почты, с которого NamelessMC будет использовать для отправки электронных писем.',
	'mailer_settings_info' => 'Следующие поля обязательны для заполнения, если вы включили PHPMailer. Для получения дополнительной информации о том, как заполнить эти поля, ознакомьтесь с <a href="https://github.com/NamelessMC/Nameless/wiki/Setting-up-SMTP-with-Nameless-(e.g.-Gmail-or-Outlook)" target="_blank">the wiki</a>.',
	'host' => 'Host',
	'email_port' => 'Port',
	'email_password_hidden' => 'Пароль не отображается из соображений безопасности.',
	'send_test_email' => 'Отправить тестовое письмо',
	'send_test_email_info' => 'Следующая кнопка попытается отправить электронное письмо на ваш электронный адрес <strong>{x}</strong>. Любые ошибки, возникшие при отправке электронного письма, будут отображены.', // Don't replace {x}
    'send' => 'Отправить',
	'test_email_error' => 'Ошибка тестового электронного письма:',
	'test_email_success' => 'Тестовое письмо успешно отправлено!',
	'terms_error' => 'Пожалуйста, введите условия не более 100 000 символов.',
	'privacy_policy_error' => 'Пожалуйста, введите политику конфиденциальности не более 100 000 символов.',
	'terms_updated' => 'Политика конфиденциальности и условия и положения успешно обновлены.',
	'avatars' => 'Аватары',
	'allow_custom_avatars' => 'Разрешить пользовательские аватары?',
	'default_avatar' => 'Аватар по умолчанию',
	'custom_avatar' => 'Пользовательский аватар',
	'minecraft_avatar' => 'Minecraft аватар',
	'minecraft_avatar_source' => 'Minecraft источник аватара',
	'built_in_avatars' => 'Встроенный сервис аватаров',
	'minecraft_avatar_perspective' => 'Майнкрафт аватар перспектива',
	'face' => 'Лицо',
	'head' => 'Голова',
	'bust' => 'Бюст',
	'select_default_avatar' => 'Выберите новый аватар по умолчанию:',
	'no_avatars_available' => 'Нет доступных аватаров. Пожалуйста, загрузите новое изображение выше в первую очередь.',
	'avatar_settings_updated_successfully' => 'Настройки аватара успешно обновлены.',
	'navigation' => 'Навигация',
	'navbar_order' => 'Порядок Навбар',
	'navbar_order_instructions' => 'Вы можете присвоить каждому элементу номер выше 0, чтобы упорядочить элементы на панели навигации, причем 1 - это первый элемент, а более высокие цифры идут после него.',
	'navbar_icon' => 'Иконка Навбар',
	'navbar_icon_instructions' => 'Вы также можете добавить значок для каждого элемента панели навигации, например, с помощью <a href="https://fontawesome.com/v4.7.0/" target="_blank" rel="noopener nofollow">Font Awesome</a>.',
	'navigation_settings_updated_successfully' => 'Настройки навигации успешно обновлены.',
	'dropdown_items' => 'Выпадающие предметы',
	'enable_page_load_timer' => 'Включить таймер загрузки страницы?',
	'google_recaptcha' => 'Включить Google reCAPTCHA?',
	'recaptcha_site_key' => 'reCAPTCHA Site Key',
	'recaptcha_secret_key' => 'reCAPTCHA Secret Key',
	'registration_disabled_message' => 'Сообщение о отключении регистрации',
	'enable_nicknames_on_registration' => 'Включить псевдонимы для регистрации пользователей?',
	'validation_promote_group' => 'Группа после проверки',
	'validation_promote_group_info' => 'Это группа, в которую пользователь будет повышен после подтверждения своей учетной записи.',
	'login_method' => 'Метод входа',
	'privacy_and_terms' => 'Защита & Условия',

	// Reactions
	'icon' => 'Иконка',
	'type' => 'Тип',
	'positive' => 'Положительный',
	'neutral' => 'Нетральный',
	'negative' => 'Отрицательный',
	'editing_reaction' => 'Редактирование Реакция',
	'html' => 'HTML',
	'new_reaction' => '<i class="fa fa-plus-circle"></i> Новая реакция',
	'creating_reaction' => 'Создание реакции',
	'no_reactions' => 'Нет никаких реакций.',
	'reaction_created_successfully' => 'Реакция успешно создана.',
	'reaction_edited_successfully' => 'Реакция успешно отредактирована.',
	'reaction_deleted_successfully' => 'Реакция успешно убалена.',
	'name_required' => 'Требуется имя',
	'html_required' => 'HTML требуется',
	'type_required' => 'Требуется тип',
	'name_maximum_16' => 'Имя должно быть не более 16 символов',
	'html_maximum_255' => 'HTML должен быть не более 255 символов',
	'confirm_delete_reaction' => 'Вы уверены, что хотите удалить эту реакцию?',

	// Пользовательские поля профиля
	'custom_fields' => 'Пользовательские поля профиля',
	'new_field' => '<i class="fa fa-plus-circle"></i> Новое поле',
	'required' => 'Необходимые',
	'editable' => 'Редактируемые',
	'public' => 'Публичные',
	'text' => 'Текст',
	'textarea' => 'Текстовая область',
	'date' => 'Дата',
	'creating_profile_field' => 'Создание поля профиля',
	'editing_profile_field' => 'Редактирование поля профиля',
	'field_name' => 'Имя поля',
	'profile_field_required_help' => 'Обязательные поля должны быть заполнены пользователем, и они появятся при регистрации.',
	'profile_field_public_help' => 'Публичные поля будут отображаться всем пользователям, если это отключено, только модераторы могут просматривать значения.',
	'profile_field_error' => 'Пожалуйста, введите имя поля длиной от 2 до 16 символов.',
	'description' => 'Описание',
	'display_field_on_forum' => 'Показать поле на форуме?',
	'profile_field_forum_help' => 'Если включено, поле будет отображаться пользователем рядом с сообщениями на форуме.',
	'profile_field_editable_help' => 'Если включено, пользователи будут иметь разрешение на редактирование поля в настройках своего профиля..',
	'no_custom_fields' => 'Нет пользовательских полей.',
	'profile_field_updated_successfully' => 'Поле профиля успешно обновлено.',
	'profile_field_created_successfully' => 'Поле профиля успешно создано.',
	'profile_field_deleted_successfully' => 'Поле профиля успешно удалено.',

	// Minecraft
	'enable_minecraft_integration' => 'Включить интеграцию Minecraft?',
	'mc_service_status' => 'Статус Майнкрафт Сервиса',
	'service_query_error' => 'Невозможно получить статус сервиса.',
	'authme_integration' => 'Интеграция с AuthMe',
	'authme_integration_info' => 'Когда включена интеграция с AuthMe, пользователи могут регистрировать только в игре.',
	'enable_authme' => 'Включить интеграцию с AuthMe?',
	'authme_db_address' => 'Адрес базы данных AuthMe',
	'authme_db_port' => 'Порт базы данных AuthMe',
	'authme_db_name' => 'Имя базы данных AuthMe',
	'authme_db_user' => 'Имя пользователя базы данных AuthMe',
	'authme_db_password' => 'Пароль базы данных AuthMe',
	'authme_db_password_hidden' => 'Пароль базы данных AuthMe скрыт по соображениям безопасности.',
	'authme_hash_algorithm' => 'AuthMe алгоритм хеширования',
	'authme_db_table' => 'Таблица пользователей AuthMe',
	'enter_authme_db_details' => 'Пожалуйста, введите действительные данные базы данных.',
	'authme_password_sync' => 'Синхронизировать пароль AuthMe?',
	'authme_password_sync_help' => 'Если включено, то всякий раз, когда пароль пользователя обновляется в игре, пароль также будет обновляться на веб-сайте.',
	'minecraft_servers' => 'Minecraft серверы',
	'account_verification' => 'Проверка учетной записи Minecraft',
	'server_banners' => 'Серверные баннеры',
	'query_errors' => 'Query ошибки',
	'add_server' => '<i class="fa fa-plus-circle"></i> Добавить сервер',
	'no_servers_defined' => 'Серверы еще не определены',
	'query_settings' => 'Query настройки',
	'default_server' => 'Сервер по умолчанию',
	'no_default_server' => 'Сервер не по умолчанию',
	'external_query' => 'Использовать внешний запрос?',
	'external_query_help' => 'Если запрос к серверу по умолчанию не работает, включите эту опцию.',
	'adding_server' => 'Добавление сервера',
	'server_name' => 'Название сервера',
	'server_address' => 'Адрес сервера',
	'server_address_help' => 'Это IP-адрес или домен, используемый для подключения к вашему серверу без порта.',
	'server_port' => 'Порт сервера',
    'parent_server' => 'Родительский сервер',
    'parent_server_help' => 'Родительский сервер обычно является экземпляром Bungee, к которому он подключен, если таковой имеется.',
    'no_parent_server' => 'Нет родительского сервера',
    'bungee_instance' => 'Экземпляр BungeeCord?',
    'bungee_instance_help' => 'Выберите эту опцию, если сервер является экземпляром BungeeCord.',
    'server_query_information' => 'In order to display a list of online players on your website, your server <strong>must</strong> have the \'enable-query\' option enabled in your server\'s <strong>server.properties</strong> file',
    'enable_status_query' => 'Включить запрос статуса?',
    'status_query_help' => 'Если это включено, на странице состояния этот сервер будет отображаться как подключенный или отключенный.',
    'enable_player_list' => 'Включить список игроков?',
    'pre_1.7' => 'Версия Minecraft старше 1.7?',
    'player_list_help' => 'Если это включено, на странице состояния будет отображаться список онлайн-игроков.',
    'server_query_port' => 'Порт Query',
    'server_query_port_help' => 'Это опция query.port в <strong>server.properties</strong> вашего сервера, если для опции enable-query в том же файле установлено значение true.',
    'server_name_required' => 'Пожалуйста, введите имя сервера',
    'server_name_minimum' => 'Убедитесь, что имя вашего сервера содержит не менее 1 символа',
    'server_name_maximum' => 'Убедитесь, что имя вашего сервера содержит не более 20 символов',
    'server_address_required' => 'Пожалуйста, введите адрес сервера',
    'server_address_minimum' => 'Пожалуйста, убедитесь, что адрес вашего сервера содержит не менее 1 символа',
    'server_address_maximum' => 'Пожалуйста, убедитесь, что адрес вашего сервера содержит не более 64 символов',
    'server_port_required' => 'Пожалуйста, введите порт сервера',
    'server_port_minimum' => 'Убедитесь, что порт вашего сервера содержит не менее 2 символов',
    'server_port_maximum' => 'Пожалуйста, убедитесь, что порт вашего сервера не более 5 символов',
    'server_parent_required' => 'Пожалуйста, выберите родительский сервер',
    'query_port_maximum' => 'Пожалуйста, убедитесь, что ваш query  порт не более 5 символов',
    'server_created' => 'Сервер успешно создан.',
    'confirm_delete_server' => 'Вы уверены, что хотите удалить этот сервер?',
	'server_updated' => 'Сервер успешно обновлен.',
	'editing_server' => 'Редактирование сервера',
	'server_deleted' => 'Сервер успешно удален',
	'unable_to_delete_server' => 'Невозможно удалить сервер.',
	'leave_port_empty_for_srv' => 'Вы можете оставить порт пустым, если он 25565, или если ваш домен использует запись SRV',
    'viewing_query_error' => 'Ошибка просмотра Query ',
    'confirm_query_error_deletion' => 'Вы уверены, что хотите удалить эту ошибку запроса?',
    'no_query_errors' => 'Нет ошибок в запросе.',
    'new_banner' => '<i class="fa fa-plus-circle"></i> Новый Баннер',
	'purge_errors' => 'Ошибки очистки',
	'confirm_purge_errors' => 'Вы уверены, что хотите удалить все ошибки?',
	'email_errors_purged_successfully' => 'Ошибки электронной почты успешно удалены.',
	'error_deleted_successfully' => 'Ошибка успешно удалена.',
	'no_email_errors' => 'Ошибки электронной почты не зарегистрированы.',
	'email_settings_updated_successfully' => 'Настройки электронной почты успешно обновлены.',
	'content' => 'Содержание',
	'mcassoc_help' => 'mcassoc - это внешний сервис, который можно использовать для проверки пользователей, имеющих учетную запись Minecraft, в которой они зарегистрированы. Чтобы использовать эту функцию, вам нужно будет подписаться на общий ключ <a href="https://mcassoc.lukegb.com/" target="_blank">here</a>.',
	'mcassoc_key' => 'mcassoc Shared Key',
	'mcassoc_instance' => 'mcassoc Instance Key',
	'mcassoc_instance_help' => '<a href="#" onclick="generateInstance();">Click to generate an instance key</a>',
	'mcassoc_error' => 'Please ensure you that have entered your shared key correctly, and that you have generated an instance key correctly.',
	'updated_mcassoc_successfully' => 'mcassoc settings updated successfully.',
	'force_premium_accounts' => 'Force premium Minecraft accounts?',
	'banner_background' => 'Banner background',
	'query_interval' => 'Query interval (in minutes, must be between 5 and 60)',
	'player_graphs' => 'Player Graphs',
	'player_count_cronjob_info' => 'You can set up a cron job to query your servers every {x} minutes with the following command:',
	'status_page' => 'Enable status page?',
	'minecraft_settings_updated_successfully' => 'Settings updated successfully.',
	'server_id_x' => 'Server ID: {x}', // Don't replace {x}
	'server_information' => 'Server Information',
	'query_information' => 'Query Information',
	'query_errors_purged_successfully' => 'Query errors purged successfully.',
	'query_error_deleted_successfully' => 'Query error deleted successfully.',
	'banner_updated_successfully' => 'Banner updated successfully. It may take a while for your changes to take effect.',

	// Modules
	'modules_installed_successfully' => 'Any new modules have been installed successfully.',
	'enabled' => 'Enabled',
	'disabled' => 'Disabled',
	'enable' => 'Enable',
	'disable' => 'Disable',
	'module_enabled' => 'Module enabled.',
	'module_disabled' => 'Module disabled.',
	'author' => 'Author:',
	'author_x' => 'Author: {x}', // Don't replace {x}
	'module_outdated' => 'We have detected that this module is intended for Nameless version {x}, but you are running Nameless version {y}', // Don't replace "{x}" or "{y}"
	'find_modules' => 'Find Modules',
	'view_all_modules' => 'View all modules',
	'unable_to_retrieve_modules' => 'Unable to retrieve modules',
	'module' => 'Module',
	'unable_to_enable_module' => 'Unable to enable incompatible module.',

	// Styles
	'templates' => 'Templates',
	'template_outdated' => 'We have detected that your template is intended for Nameless version {x}, but you are running Nameless version {y}', // Don't replace "{x}" or "{y}"
	'active' => 'Active',
	'deactivate' => 'Deactivate',
	'activate' => 'Activate',
	'warning_editing_default_template' => 'Warning! It is recommended that you do not edit the default template.',
	'images' => 'Images',
	'upload_new_image' => 'Upload New Image',
	'reset_background' => 'Reset Background',
	'install' => '<i class="fa fa-plus-circle"></i> Install',
	'template_updated' => 'Template successfully updated.',
	'default' => 'Default',
	'make_default' => 'Make Default',
	'default_template_set' => 'Default template set to {x} successfully.', // Don't replace {x}
	'template_deactivated' => 'Template deactivated.',
	'template_activated' => 'Template activated.',
	'permissions' => 'Permissions',
	'setting_perms_for_x' => 'Setting permissions for template {x}', // Don't replace {x}
	'templates_installed_successfully' => 'Any new templates have been installed successfully.',
	'confirm_delete_template' => 'Are you sure you want to delete this template?',
	'delete' => 'Delete',
	'template_deleted_successfully' => 'Template deleted successfully.',
	'background_image_x' => 'Background image: <strong>{x}</strong>', // Don't replace {x}
	'find_templates' => 'Find Templates',
	'view_all_templates' => 'View all templates',
	'unable_to_retrieve_templates' => 'Unable to retrieve templates',
	'template' => 'Template',
	'stats' => 'Stats',
	'downloads_x' => 'Downloads: {x}',
	'views_x' => 'Views: {x}',
	'rating_x' => 'Rating: {x}',
	'editing_template_x' => 'Editing template {x}', // Don't replace {x}
	'editing_template_file_in_template' => 'Editing file {x} in template {y}', // Don't replace {x} or {y}
	'cant_write_to_template' => 'Can\'t write to template file! Please check file permissions.',
	'unable_to_delete_template' => 'Unable to fully delete template. Please check file permissions.',
	'background_reset_successfully' => 'Background reset successfully.',
	'background_updated_successfully' => 'Background updated successfully.',
	'unable_to_enable_template' => 'Unable to enable incompatible template.',

	// Users & groups
	'users' => 'Users',
	'groups' => 'Groups',
	'group' => 'Group',
	'new_user' => '<i class="fa fa-plus-circle"></i> New User',
	'creating_new_user' => 'Creating new user',
	'registered' => 'Registered',
	'user_created' => 'User created successfully.',
	'cant_delete_root_user' => 'Can\'t delete the root user!',
	'cant_modify_root_user' => 'Can\'t modify this user\'s group!',
	'user_deleted' => 'User deleted successfully.',
	'confirm_user_deletion' => 'Are you sure you want to delete the user <strong>{x}</strong>?', // Don't replace {x}
	'validate_user' => 'Validate User',
	'update_uuid' => 'Update UUID',
	'update_mc_name' => 'Update Minecraft Username',
	'reset_password' => 'Reset Password',
	'punish_user' => 'Punish User',
	'delete_user' => 'Delete User',
	'minecraft_uuid' => 'Minecraft UUID',
	'other_actions' => 'Other Actions',
	'disable_avatar' => 'Disable Avatar',
	'select_user_group' => 'You must select a user\'s group.',
	'uuid_max_32' => 'The UUID must be a maximum of 32 characters.',
	'title_max_64' => 'The user title must be a maximum of 64 characters.',
	'group_id' => 'Group ID',
	'name' => 'Name',
	'title' => 'User Title',
	'new_group' => '<i class="fa fa-plus-circle"></i> New Group',
	'group_name_required' => 'Please input a group name.',
	'group_name_minimum' => 'Please ensure your group name is a minimum of 2 characters long.',
	'group_name_maximum' => 'Please ensure your group name is a maximum of 20 characters long.',
	'creating_group' => 'Creating new group',
	'group_html_maximum' => 'Please ensure your group HTML is no longer than 1024 characters long.',
	'group_html' => 'Group HTML',
	'group_html_lg' => 'Group HTML Large',
	'group_username_colour' => 'Group Username Colour',
	'group_staff' => 'Is the group a staff group?',
	'group_modcp' => 'Can the group view the ModCP?',
	'group_admincp' => 'Can the group view the AdminCP?',
	'delete_group' => 'Delete Group',
	'confirm_group_deletion' => 'Are you sure you want to delete the group {x}?', // Don't replace {x}
	'group_not_exist' => 'That group doesn\'t exist.',
	'secondary_groups' => 'Secondary Groups',
	'secondary_groups_info' => 'The user will gain any additional permissions from these groups. Ctrl+click to select/deselect multiple groups.',
	'unable_to_update_uuid' => 'Unable to update UUID.',
	'default_group' => 'Is the group the default group (for new users)?',
	'user_id' => 'User ID',
	'uuid' => 'UUID',
	'group_order' => 'Group Order',
	'group_created_successfully' => 'Group created successfully.',
	'group_updated_successfully' => 'Group updated successfully.',
	'group_deleted_successfully' => 'Group deleted successfully.',
	'unable_to_delete_group' => 'Unable to delete a default group, or a group that can view the StaffCP. Please update the group settings first!',
	'can_view_staffcp' => 'Can the group view the StaffCP?',
	'user' => 'User',
	'user_validated_successfully' => 'User validated successfully.',
	'user_updated_successfully' => 'User updated successfully,',
	'editing_user_x' => 'Editing user {x}', // Don't replace {x}
	'details' => 'Details',

	// Permissions
	'select_all' => 'Select All',
	'deselect_all' => 'Deselect All',
	'background_image' => 'Background image',
	'can_edit_own_group' => 'Can edit own group\'s permissions',
	'permissions_updated_successfully' => 'Permissions updated successfully.',
	'cant_edit_this_group' => 'You can\'t edit this group\'s permissions!',

	// General Admin language
	'task_successful' => 'Task successful.',
	'invalid_action' => 'Invalid action.',
	'enable_night_mode' => 'Enable Night Mode',
	'disable_night_mode' => 'Disable Night Mode',
	'view_site' => 'View Site',
	'signed_in_as_x' => 'Signed in as {x}', // Don't replace {x}
    'warning' => 'Warning',

    // Maintenance
    'maintenance_mode' => 'Maintenance Mode',
    'maintenance_enabled' => 'Maintenance mode is currently enabled.',
    'enable_maintenance_mode' => 'Enable maintenance mode?',
    'maintenance_mode_message' => 'Maintenance mode message',
    'maintenance_message_max_1024' => 'Please ensure your maintenance message is a maximum of 1024 characters.',

	// Security
	'acp_logins' => 'AdminCP Logins',
	'please_select_logs' => 'Please select logs to view',
	'ip_address' => 'IP Address',
	'template_changes' => 'Template Changes',
	'file_changed' => 'File Changed',
	'all_logs' => 'All Logs',
	'action' => 'Action',
	'action_info' => 'Action Info',
    
	// Updates
	'update' => 'Update',
	'current_version_x' => 'Current version: <strong>{x}</strong>', // Don't replace {x}
	'new_version_x' => 'New version: <strong>{x}</strong>', // Don't replace {x}
	'new_update_available' => 'There is a new update available.',
	'new_urgent_update_available' => 'There is a new urgent update available. Please update as soon as possible!',
	'up_to_date' => 'Your NamelessMC installation is up to date!',
	'urgent' => 'This update is an urgent update',
	'changelog' => 'Changelog',
	'update_check_error' => 'There was an error whilst checking for an update:',
	'instructions' => 'Instructions',
	'download' => 'Download',
	'install_confirm' => 'Please ensure you have downloaded the package and uploaded the contained files first!',
	'check_again' => 'Check again',

	// Widgets
	'widgets' => 'Widgets',
	'widget_enabled' => 'Widget enabled.',
	'widget_disabled' => 'Widget disabled.',
	'widget_updated' => 'Widget updated.',
	'editing_widget_x' => 'Editing widget {x}', // Don't replace {x}
	'module_x' => 'Module: {x}', // Don't replace {x}
	'widget_order' => 'Widget Order',

    // Online users widget
    'include_staff_in_user_widget' => 'Include staff members in user widget?',

	// Custom Pages
	'pages' => 'Pages',
	'custom_pages' => 'Custom Pages',
	'new_page' => '<i class="fa fa-plus-circle"></i> New Page',
	'no_custom_pages' => 'No pages have been created yet.',
	'creating_new_page' => 'Creating Page',
	'page_title' => 'Page Title',
	'page_path' => 'Page Path (with preceding /, eg /example)',
	'page_icon' => 'Page Icon',
	'page_link_location' => 'Page Link Location',
	'page_link_navbar' => 'Navbar',
	'page_link_footer' => 'Footer',
	'page_link_more' => '"More" Dropdown',
	'page_link_none' => 'No link',
	'page_content' => 'Page Content',
	'page_redirect' => 'Page Redirect?',
	'page_redirect_to' => 'Redirect Link (with preceding http://)',
	'unsafe_html' => 'Allow unsafe HTML?',
	'unsafe_html_warning' => 'Enabling this option means any HTML can be used on the page, including potentially dangerous JavaScript. Only enable this if you are sure your HTML is safe.',
	'include_in_sitemap' => 'Include in sitemap?',
	'sitemap_link' => 'Sitemap link:',
	'page_permissions' => 'Page Permissions',
	'view_page' => 'View Page?',
	'editing_page_x' => 'Editing Page {x}', // Don't replace {x}
    'unable_to_create_page' => 'Unable to create page:',
	'page_title_required' => 'A page title is required.',
	'page_url_required' => 'A page path is required.',
	'link_location_required' => 'A link location is required.',
	'page_title_minimum_2' => 'The page title must be a minimum of 2 characters.',
	'page_url_minimum_2' => 'The page path must be a minimum of 2 characters.',
	'page_title_maximum_30' => 'The page title must be a maximum of 30 characters.',
	'page_icon_maximum_64' => 'The page icon must be a maximum of 64 characters.',
	'page_url_maximum_20' => 'The page path must be a maximum of 20 characters.',
	'page_content_maximum_100000' => 'The page content must be a maximum of 100000 characters.',
	'page_redirect_link_maximum_512' => 'The page redirect link must be a maximum of 512 characters.',
	'confirm_delete_page' => 'Are you sure you want to delete this page?',
	'page_created_successfully' => 'Page created successfully.',
	'page_updated_successfully' => 'Page updated successfully.',
	'page_deleted_successfully' => 'Page deleted successfully.',

	// API
    'api' => 'API',
	'enable_api' => 'Enable API?',
	'api_info' => 'The API allows for plugins and other services to interact with your website, such as the <a href="https://namelessmc.com/resources/resource/5-namelessplugin/" target="_blank" >official Nameless plugin</a>.',
	'enable_legacy_api' => 'Enable legacy API?',
	'legacy_api_info' => 'The legacy API allows plugins which use the old Nameless version 1 API to work with your version 2 website.',
	'confirm_api_regen' => 'Are you sure you want to regenerate your API key?',
	'api_key' => 'API Key',
	'api_url' => 'API URL',
	'copy' => 'Copy',
	'api_key_regenerated' => 'The API key has been regenerated successfully.',
	'api_registration_email' => 'API Registration Email',
	'show_registration_link' => 'Show registration link',
	'registration_link' => 'Registration Link',
	'link_to_complete_registration' => 'Link to complete registration: {x}', // Don't replace {x}
	'api_verification' => 'Enable API verification?',
	'api_verification_info' => 'If enabled, accounts can only be verified through the API, for example ingame using the official Nameless plugin. <strong>This option will override email verification, and accounts will be automatically activated!</strong><br />You should set up your default group to have limited permissions, and then update the post-validation group in the AdminCP -> Core -> Registration tab to the full member group with normal permissions.',
	'enable_username_sync' => 'Enable username sync?',
	'enable_username_sync_info' => 'If enabled, website usernames will be updated to match ingame usernames.',
	'api_settings_updated_successfully' => 'API settings updated successfully.',
	'group_sync' => 'Group Sync',
	'group_sync_info' => 'You can configure the API to automatically update a user\'s website group when their ingame group is changed. Simply enter the ingame group name and the website group it should be synchronised with below.',
	'ingame_group' => 'Ingame Group Name',
	'website_group' => 'Website Group',
	'set_as_primary_group' => 'Set as primary group?',
	'set_as_primary_group_info' => 'If enabled, the user\'s primary website group will be updated. If disabled, the ingame group will be added to the user\'s website secondary groups.',
	'ingame_group_maximum' => 'Please ensure your group name is a maximum of 64 characters long.',
	'select_website_group' => 'Please select a website group.',
	'ingame_group_already_exists' => 'A rank sync rule has already been created for that ingame group.',
	'group_sync_rule_created_successfully' => 'The group sync rule has been created successfully.',
	'group_sync_rules_updated_successfully' => 'Group sync rules have been updated successfully.',
	'group_sync_rule_deleted_successfully' => 'The group sync rule has been deleted successfully.',
	'existing_rules' => 'Existing Rules',
	'new_rule' => 'New Rule',

	// File uploads
	'drag_files_here' => 'Drag files here to upload.',
	'invalid_file_type' => 'Invalid file type!',
	'file_too_big' => 'File too big! Your file was {{filesize}} and the limit is {{maxFilesize}}', // Don't replace {{filesize}} or {{maxFilesize}}
	'allowed_proxies' => 'Allowed Proxies',
	'allowed_proxies_info' => 'Line separated list of allowed proxy IPs.',

	// Error logs
	'error_logs' => 'Error Logs',
	'notice_log' => 'Notice log',
	'warning_log' => 'Warning log',
	'custom_log' => 'Custom log',
	'other_log' => 'Other log',
	'fatal_log' => 'Fatal log',
	'log_file_not_found' => 'Log file not found.',
	'log_purged_successfully' => 'The log has been purged successfully.',

	// Hooks
	'discord_hooks' => 'Discord Hooks',
	'discord_hooks_info' => 'Send a message to a Discord channel when something happens on your site. Create a Discord hook in your Discord Server Settings -> Webhooks tab.',
	'discord_hook_url' => 'Discord webhook URL',
	'discord_hook_events' => 'Enabled Discord hook events (Ctrl+click to select multiple events)',
	'register_hook_info' => 'User registration',
	'validate_hook_info' => 'User validation',
	'delete_hook_info' => 'User deletion',

	// Sitemap
	'unable_to_load_sitemap_file_x' => 'Unable to load sitemap file {x}', // Don't replace {x}
	'sitemap_generated' => 'Sitemap generated successfully',
	'sitemap_not_writable' => 'The <strong>cache/sitemaps</strong> directory is not writable.',
	'cache_not_writable' => 'The <strong>cache</strong> directory is not writable.',
	'generate_sitemap' => 'Generate Sitemap',
	'download_sitemap' => 'Download Sitemap',
	'sitemap_not_generated_yet' => 'A sitemap has not been generated yet!',
	'sitemap_last_generated_x' => 'The sitemap was last generated {x}', // Don't replace {x}

	// Page metadata
	'page_metadata' => 'Page Metadata',
	'metadata_page_x' => 'Viewing metadata for page {x}', // Don't replace {x}
	'keywords' => 'Keywords',
	'description_max_500' => 'The description must be at most 500 characters.',
	'page' => 'Page',
	'metadata_updated_successfully' => 'Metadata updated successfully.',

	// Dashboard
	'total_users' => 'Total Users',
	'total_users_statistic_icon' => '<i class="fas fa-users"></i>',
	'recent_users' => 'New Users',
	'recent_users_statistic_icon' => '<i class="fas fa-users"></i>',
	'average_players' => 'Average Players',
	'nameless_news' => 'NamelessMC News',
	'unable_to_retrieve_nameless_news' => 'Unable to retrieve the latest news',
	'confirm_leave_site' => 'You are about to leave this site! Are you sure you want to visit <strong id="leaveSiteURL">{x}</strong>?', // don't replace {x} and make sure it has the id leaveSiteURL
	'server_compatibility' => 'Server Compatibility',
	'issues' => 'Issues',

	// Other
	'source' => 'Source',
	'support' => 'Support',
	'admin_dir_still_exists' => 'Warning! The <strong>modules/Core/pages/admin</strong> directory still exists. Please remove this directory.',
	'mod_dir_still_exists' => 'Warning! The <strong>modules/Core/pages/mod</strong> directory still exists. Please remove this directory.'
);
